# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
jobs:
  build:
    working_directory: ~/maxwellkendall.com
    docker:
      - image: "circleci/node:10.15.3"
    steps:
      - checkout
      - run:
          name: "install dependencies"
          command: "npm install"
      - run:
          name: "build code"
          command: "npm run build"
          environment:
            CONTENTFUL_SPACE_ID: "b9r33i3rvu3z"
            CONTENTFUL_DELIVERY_TOKEN: "99b97289fcd220b19dececcdfc13794c62cc149ee7f355b206ed56515755de74"
  deploy:
    working_directory: ~/maxwellkendall.com/public
    docker:
      - image: "circleci/python:2.7"
    steps:
      - run:
          name: "install the awscli"
          command: "sudo pip install aws-cli"
      - run:
          name: "upload the build files using aws cli"
          command: "aws s3 . s3://maxwellkendall.com --region us-east-1 --acl public-read"
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
